
namespace Login_Template
{
    partial class Home
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Home));
            this.panel1 = new System.Windows.Forms.Panel();
            this.lblTop = new System.Windows.Forms.Label();
            this.btnEpandandClose = new System.Windows.Forms.PictureBox();
            this.sideBar = new System.Windows.Forms.Panel();
            this.btnCategories = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnModels = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnCollection = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnHome = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel3 = new System.Windows.Forms.Panel();
            this.pictureBox2 = new System.Windows.Forms.PictureBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.btnPhotos = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnVIP = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnPlaylist = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnRequest = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnChat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAbout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.panel2 = new System.Windows.Forms.Panel();
            this.btnClose = new System.Windows.Forms.PictureBox();
            this.btnRestoreDown = new System.Windows.Forms.PictureBox();
            this.btnMinimize = new System.Windows.Forms.PictureBox();
            this.btnMaximize = new System.Windows.Forms.PictureBox();
            this.homeController1 = new Login_Template.homeController();
            this.collectionController1 = new Login_Template.collectionController();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.btnEpandandClose)).BeginInit();
            this.sideBar.SuspendLayout();
            this.panel3.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).BeginInit();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.btnClose)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnRestoreDown)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnMinimize)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnMaximize)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(86)))), ((int)(((byte)(182)))));
            this.panel1.Controls.Add(this.panel2);
            this.panel1.Controls.Add(this.lblTop);
            this.panel1.Controls.Add(this.btnEpandandClose);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(749, 43);
            this.panel1.TabIndex = 0;
            this.panel1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.panel1_MouseDown);
            // 
            // lblTop
            // 
            this.lblTop.AutoSize = true;
            this.lblTop.Font = new System.Drawing.Font("Century Gothic", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblTop.ForeColor = System.Drawing.Color.White;
            this.lblTop.Location = new System.Drawing.Point(49, 9);
            this.lblTop.Name = "lblTop";
            this.lblTop.Size = new System.Drawing.Size(64, 22);
            this.lblTop.TabIndex = 1;
            this.lblTop.Text = "Home";
            // 
            // btnEpandandClose
            // 
            this.btnEpandandClose.Image = ((System.Drawing.Image)(resources.GetObject("btnEpandandClose.Image")));
            this.btnEpandandClose.Location = new System.Drawing.Point(13, 6);
            this.btnEpandandClose.Name = "btnEpandandClose";
            this.btnEpandandClose.Size = new System.Drawing.Size(30, 30);
            this.btnEpandandClose.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.btnEpandandClose.TabIndex = 0;
            this.btnEpandandClose.TabStop = false;
            this.btnEpandandClose.Click += new System.EventHandler(this.btnEpandandClose_Click);
            // 
            // sideBar
            // 
            this.sideBar.BackColor = System.Drawing.Color.WhiteSmoke;
            this.sideBar.Controls.Add(this.btnAbout);
            this.sideBar.Controls.Add(this.btnChat);
            this.sideBar.Controls.Add(this.btnRequest);
            this.sideBar.Controls.Add(this.btnPlaylist);
            this.sideBar.Controls.Add(this.btnVIP);
            this.sideBar.Controls.Add(this.btnPhotos);
            this.sideBar.Controls.Add(this.btnCategories);
            this.sideBar.Controls.Add(this.btnModels);
            this.sideBar.Controls.Add(this.btnCollection);
            this.sideBar.Controls.Add(this.btnHome);
            this.sideBar.Controls.Add(this.panel3);
            this.sideBar.Dock = System.Windows.Forms.DockStyle.Left;
            this.sideBar.Location = new System.Drawing.Point(0, 43);
            this.sideBar.Name = "sideBar";
            this.sideBar.Size = new System.Drawing.Size(162, 507);
            this.sideBar.TabIndex = 1;
            this.sideBar.Paint += new System.Windows.Forms.PaintEventHandler(this.sideBar_Paint);
            // 
            // btnCategories
            // 
            this.btnCategories.AllowAnimations = true;
            this.btnCategories.AllowMouseEffects = true;
            this.btnCategories.AllowToggling = false;
            this.btnCategories.AnimationSpeed = 200;
            this.btnCategories.AutoGenerateColors = false;
            this.btnCategories.AutoRoundBorders = false;
            this.btnCategories.AutoSizeLeftIcon = true;
            this.btnCategories.AutoSizeRightIcon = true;
            this.btnCategories.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.btnCategories.BackColor = System.Drawing.Color.Transparent;
            this.btnCategories.BackColor1 = System.Drawing.Color.Transparent;
            this.btnCategories.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCategories.BackgroundImage")));
            this.btnCategories.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategories.ButtonText = "Categories";
            this.btnCategories.ButtonTextMarginLeft = 0;
            this.btnCategories.ColorContrastOnClick = 45;
            this.btnCategories.ColorContrastOnHover = 45;
            this.btnCategories.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnCategories.CustomizableEdges = borderEdges7;
            this.btnCategories.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCategories.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCategories.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCategories.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCategories.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnCategories.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCategories.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCategories.ForeColor = System.Drawing.Color.Black;
            this.btnCategories.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCategories.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCategories.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCategories.IconMarginLeft = 11;
            this.btnCategories.IconPadding = 10;
            this.btnCategories.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCategories.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCategories.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCategories.IconSize = 100;
            this.btnCategories.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnCategories.IdleBorderRadius = 1;
            this.btnCategories.IdleBorderThickness = 1;
            this.btnCategories.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnCategories.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnCategories.IdleIconLeftImage")));
            this.btnCategories.IdleIconRightImage = null;
            this.btnCategories.IndicateFocus = false;
            this.btnCategories.Location = new System.Drawing.Point(0, 194);
            this.btnCategories.Name = "btnCategories";
            this.btnCategories.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCategories.OnDisabledState.BorderRadius = 1;
            this.btnCategories.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategories.OnDisabledState.BorderThickness = 1;
            this.btnCategories.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCategories.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCategories.OnDisabledState.IconLeftImage = null;
            this.btnCategories.OnDisabledState.IconRightImage = null;
            this.btnCategories.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCategories.onHoverState.BorderRadius = 1;
            this.btnCategories.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategories.onHoverState.BorderThickness = 1;
            this.btnCategories.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCategories.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCategories.onHoverState.IconLeftImage = null;
            this.btnCategories.onHoverState.IconRightImage = null;
            this.btnCategories.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnCategories.OnIdleState.BorderRadius = 1;
            this.btnCategories.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategories.OnIdleState.BorderThickness = 1;
            this.btnCategories.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnCategories.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnCategories.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.OnIdleState.IconLeftImage")));
            this.btnCategories.OnIdleState.IconRightImage = null;
            this.btnCategories.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCategories.OnPressedState.BorderRadius = 1;
            this.btnCategories.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCategories.OnPressedState.BorderThickness = 1;
            this.btnCategories.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCategories.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCategories.OnPressedState.IconLeftImage = null;
            this.btnCategories.OnPressedState.IconRightImage = null;
            this.btnCategories.Size = new System.Drawing.Size(162, 41);
            this.btnCategories.TabIndex = 7;
            this.btnCategories.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCategories.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCategories.TextMarginLeft = 0;
            this.btnCategories.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCategories.UseDefaultRadiusAndThickness = true;
            this.btnCategories.Click += new System.EventHandler(this.btnCategories_Click);
            // 
            // btnModels
            // 
            this.btnModels.AllowAnimations = true;
            this.btnModels.AllowMouseEffects = true;
            this.btnModels.AllowToggling = false;
            this.btnModels.AnimationSpeed = 200;
            this.btnModels.AutoGenerateColors = false;
            this.btnModels.AutoRoundBorders = false;
            this.btnModels.AutoSizeLeftIcon = true;
            this.btnModels.AutoSizeRightIcon = true;
            this.btnModels.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.btnModels.BackColor = System.Drawing.Color.Transparent;
            this.btnModels.BackColor1 = System.Drawing.Color.Transparent;
            this.btnModels.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnModels.BackgroundImage")));
            this.btnModels.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModels.ButtonText = "Models";
            this.btnModels.ButtonTextMarginLeft = 0;
            this.btnModels.ColorContrastOnClick = 45;
            this.btnModels.ColorContrastOnHover = 45;
            this.btnModels.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnModels.CustomizableEdges = borderEdges8;
            this.btnModels.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnModels.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModels.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModels.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModels.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnModels.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnModels.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnModels.ForeColor = System.Drawing.Color.Black;
            this.btnModels.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnModels.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnModels.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnModels.IconMarginLeft = 11;
            this.btnModels.IconPadding = 10;
            this.btnModels.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnModels.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnModels.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnModels.IconSize = 100;
            this.btnModels.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnModels.IdleBorderRadius = 1;
            this.btnModels.IdleBorderThickness = 1;
            this.btnModels.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnModels.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnModels.IdleIconLeftImage")));
            this.btnModels.IdleIconRightImage = null;
            this.btnModels.IndicateFocus = false;
            this.btnModels.Location = new System.Drawing.Point(0, 153);
            this.btnModels.Name = "btnModels";
            this.btnModels.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnModels.OnDisabledState.BorderRadius = 1;
            this.btnModels.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModels.OnDisabledState.BorderThickness = 1;
            this.btnModels.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnModels.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnModels.OnDisabledState.IconLeftImage = null;
            this.btnModels.OnDisabledState.IconRightImage = null;
            this.btnModels.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModels.onHoverState.BorderRadius = 1;
            this.btnModels.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModels.onHoverState.BorderThickness = 1;
            this.btnModels.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnModels.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnModels.onHoverState.IconLeftImage = null;
            this.btnModels.onHoverState.IconRightImage = null;
            this.btnModels.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnModels.OnIdleState.BorderRadius = 1;
            this.btnModels.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModels.OnIdleState.BorderThickness = 1;
            this.btnModels.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnModels.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnModels.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.OnIdleState.IconLeftImage")));
            this.btnModels.OnIdleState.IconRightImage = null;
            this.btnModels.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnModels.OnPressedState.BorderRadius = 1;
            this.btnModels.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnModels.OnPressedState.BorderThickness = 1;
            this.btnModels.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnModels.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnModels.OnPressedState.IconLeftImage = null;
            this.btnModels.OnPressedState.IconRightImage = null;
            this.btnModels.Size = new System.Drawing.Size(162, 41);
            this.btnModels.TabIndex = 6;
            this.btnModels.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnModels.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnModels.TextMarginLeft = 0;
            this.btnModels.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnModels.UseDefaultRadiusAndThickness = true;
            this.btnModels.Click += new System.EventHandler(this.btnModels_Click);
            // 
            // btnCollection
            // 
            this.btnCollection.AllowAnimations = true;
            this.btnCollection.AllowMouseEffects = true;
            this.btnCollection.AllowToggling = false;
            this.btnCollection.AnimationSpeed = 200;
            this.btnCollection.AutoGenerateColors = false;
            this.btnCollection.AutoRoundBorders = false;
            this.btnCollection.AutoSizeLeftIcon = true;
            this.btnCollection.AutoSizeRightIcon = true;
            this.btnCollection.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.btnCollection.BackColor = System.Drawing.Color.Transparent;
            this.btnCollection.BackColor1 = System.Drawing.Color.Transparent;
            this.btnCollection.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnCollection.BackgroundImage")));
            this.btnCollection.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCollection.ButtonText = "Collection";
            this.btnCollection.ButtonTextMarginLeft = 0;
            this.btnCollection.ColorContrastOnClick = 45;
            this.btnCollection.ColorContrastOnHover = 45;
            this.btnCollection.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnCollection.CustomizableEdges = borderEdges9;
            this.btnCollection.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnCollection.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCollection.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCollection.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCollection.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnCollection.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnCollection.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnCollection.ForeColor = System.Drawing.Color.Black;
            this.btnCollection.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnCollection.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnCollection.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnCollection.IconMarginLeft = 11;
            this.btnCollection.IconPadding = 10;
            this.btnCollection.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnCollection.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnCollection.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnCollection.IconSize = 100;
            this.btnCollection.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnCollection.IdleBorderRadius = 1;
            this.btnCollection.IdleBorderThickness = 1;
            this.btnCollection.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnCollection.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnCollection.IdleIconLeftImage")));
            this.btnCollection.IdleIconRightImage = null;
            this.btnCollection.IndicateFocus = false;
            this.btnCollection.Location = new System.Drawing.Point(0, 112);
            this.btnCollection.Name = "btnCollection";
            this.btnCollection.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnCollection.OnDisabledState.BorderRadius = 1;
            this.btnCollection.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCollection.OnDisabledState.BorderThickness = 1;
            this.btnCollection.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnCollection.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnCollection.OnDisabledState.IconLeftImage = null;
            this.btnCollection.OnDisabledState.IconRightImage = null;
            this.btnCollection.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCollection.onHoverState.BorderRadius = 1;
            this.btnCollection.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCollection.onHoverState.BorderThickness = 1;
            this.btnCollection.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnCollection.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnCollection.onHoverState.IconLeftImage = null;
            this.btnCollection.onHoverState.IconRightImage = null;
            this.btnCollection.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnCollection.OnIdleState.BorderRadius = 1;
            this.btnCollection.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCollection.OnIdleState.BorderThickness = 1;
            this.btnCollection.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnCollection.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnCollection.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.OnIdleState.IconLeftImage")));
            this.btnCollection.OnIdleState.IconRightImage = null;
            this.btnCollection.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnCollection.OnPressedState.BorderRadius = 1;
            this.btnCollection.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnCollection.OnPressedState.BorderThickness = 1;
            this.btnCollection.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnCollection.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnCollection.OnPressedState.IconLeftImage = null;
            this.btnCollection.OnPressedState.IconRightImage = null;
            this.btnCollection.Size = new System.Drawing.Size(162, 41);
            this.btnCollection.TabIndex = 5;
            this.btnCollection.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnCollection.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnCollection.TextMarginLeft = 0;
            this.btnCollection.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnCollection.UseDefaultRadiusAndThickness = true;
            this.btnCollection.Click += new System.EventHandler(this.btnCollection_Click);
            // 
            // btnHome
            // 
            this.btnHome.AllowAnimations = true;
            this.btnHome.AllowMouseEffects = true;
            this.btnHome.AllowToggling = false;
            this.btnHome.AnimationSpeed = 200;
            this.btnHome.AutoGenerateColors = false;
            this.btnHome.AutoRoundBorders = false;
            this.btnHome.AutoSizeLeftIcon = true;
            this.btnHome.AutoSizeRightIcon = true;
            this.btnHome.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.btnHome.BackColor = System.Drawing.Color.Transparent;
            this.btnHome.BackColor1 = System.Drawing.Color.Transparent;
            this.btnHome.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnHome.BackgroundImage")));
            this.btnHome.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.ButtonText = "Home";
            this.btnHome.ButtonTextMarginLeft = 0;
            this.btnHome.ColorContrastOnClick = 45;
            this.btnHome.ColorContrastOnHover = 45;
            this.btnHome.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.btnHome.CustomizableEdges = borderEdges10;
            this.btnHome.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnHome.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHome.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHome.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHome.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnHome.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnHome.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnHome.ForeColor = System.Drawing.Color.Black;
            this.btnHome.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnHome.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnHome.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnHome.IconMarginLeft = 11;
            this.btnHome.IconPadding = 10;
            this.btnHome.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnHome.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnHome.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnHome.IconSize = 100;
            this.btnHome.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnHome.IdleBorderRadius = 1;
            this.btnHome.IdleBorderThickness = 1;
            this.btnHome.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnHome.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnHome.IdleIconLeftImage")));
            this.btnHome.IdleIconRightImage = null;
            this.btnHome.IndicateFocus = false;
            this.btnHome.Location = new System.Drawing.Point(0, 71);
            this.btnHome.Name = "btnHome";
            this.btnHome.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnHome.OnDisabledState.BorderRadius = 1;
            this.btnHome.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.OnDisabledState.BorderThickness = 1;
            this.btnHome.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnHome.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnHome.OnDisabledState.IconLeftImage = null;
            this.btnHome.OnDisabledState.IconRightImage = null;
            this.btnHome.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnHome.onHoverState.BorderRadius = 1;
            this.btnHome.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.onHoverState.BorderThickness = 1;
            this.btnHome.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnHome.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnHome.onHoverState.IconLeftImage = null;
            this.btnHome.onHoverState.IconRightImage = null;
            this.btnHome.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnHome.OnIdleState.BorderRadius = 1;
            this.btnHome.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.OnIdleState.BorderThickness = 1;
            this.btnHome.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnHome.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnHome.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.OnIdleState.IconLeftImage")));
            this.btnHome.OnIdleState.IconRightImage = null;
            this.btnHome.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnHome.OnPressedState.BorderRadius = 1;
            this.btnHome.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnHome.OnPressedState.BorderThickness = 1;
            this.btnHome.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnHome.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnHome.OnPressedState.IconLeftImage = null;
            this.btnHome.OnPressedState.IconRightImage = null;
            this.btnHome.Size = new System.Drawing.Size(162, 41);
            this.btnHome.TabIndex = 3;
            this.btnHome.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnHome.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnHome.TextMarginLeft = 0;
            this.btnHome.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnHome.UseDefaultRadiusAndThickness = true;
            this.btnHome.Click += new System.EventHandler(this.btnHome_Click);
            // 
            // panel3
            // 
            this.panel3.Controls.Add(this.pictureBox2);
            this.panel3.Controls.Add(this.label3);
            this.panel3.Controls.Add(this.label2);
            this.panel3.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel3.Location = new System.Drawing.Point(0, 0);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(162, 71);
            this.panel3.TabIndex = 4;
            // 
            // pictureBox2
            // 
            this.pictureBox2.BackColor = System.Drawing.Color.Transparent;
            this.pictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("pictureBox2.Image")));
            this.pictureBox2.Location = new System.Drawing.Point(3, 6);
            this.pictureBox2.Name = "pictureBox2";
            this.pictureBox2.Size = new System.Drawing.Size(58, 59);
            this.pictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.pictureBox2.TabIndex = 4;
            this.pictureBox2.TabStop = false;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.Gray;
            this.label3.Location = new System.Drawing.Point(82, 42);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(33, 17);
            this.label3.TabIndex = 3;
            this.label3.Text = "City";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.ForeColor = System.Drawing.Color.Gray;
            this.label2.Location = new System.Drawing.Point(82, 15);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(71, 17);
            this.label2.TabIndex = 2;
            this.label2.Text = "Username";
            // 
            // btnPhotos
            // 
            this.btnPhotos.AllowAnimations = true;
            this.btnPhotos.AllowMouseEffects = true;
            this.btnPhotos.AllowToggling = false;
            this.btnPhotos.AnimationSpeed = 200;
            this.btnPhotos.AutoGenerateColors = false;
            this.btnPhotos.AutoRoundBorders = false;
            this.btnPhotos.AutoSizeLeftIcon = true;
            this.btnPhotos.AutoSizeRightIcon = true;
            this.btnPhotos.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.btnPhotos.BackColor = System.Drawing.Color.Transparent;
            this.btnPhotos.BackColor1 = System.Drawing.Color.Transparent;
            this.btnPhotos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPhotos.BackgroundImage")));
            this.btnPhotos.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPhotos.ButtonText = "Photos";
            this.btnPhotos.ButtonTextMarginLeft = 0;
            this.btnPhotos.ColorContrastOnClick = 45;
            this.btnPhotos.ColorContrastOnHover = 45;
            this.btnPhotos.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnPhotos.CustomizableEdges = borderEdges6;
            this.btnPhotos.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPhotos.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPhotos.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPhotos.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPhotos.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnPhotos.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPhotos.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPhotos.ForeColor = System.Drawing.Color.Black;
            this.btnPhotos.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPhotos.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPhotos.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPhotos.IconMarginLeft = 11;
            this.btnPhotos.IconPadding = 10;
            this.btnPhotos.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPhotos.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPhotos.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPhotos.IconSize = 100;
            this.btnPhotos.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnPhotos.IdleBorderRadius = 1;
            this.btnPhotos.IdleBorderThickness = 1;
            this.btnPhotos.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnPhotos.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnPhotos.IdleIconLeftImage")));
            this.btnPhotos.IdleIconRightImage = null;
            this.btnPhotos.IndicateFocus = false;
            this.btnPhotos.Location = new System.Drawing.Point(0, 235);
            this.btnPhotos.Name = "btnPhotos";
            this.btnPhotos.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPhotos.OnDisabledState.BorderRadius = 1;
            this.btnPhotos.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPhotos.OnDisabledState.BorderThickness = 1;
            this.btnPhotos.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPhotos.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPhotos.OnDisabledState.IconLeftImage = null;
            this.btnPhotos.OnDisabledState.IconRightImage = null;
            this.btnPhotos.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnPhotos.onHoverState.BorderRadius = 1;
            this.btnPhotos.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPhotos.onHoverState.BorderThickness = 1;
            this.btnPhotos.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnPhotos.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnPhotos.onHoverState.IconLeftImage = null;
            this.btnPhotos.onHoverState.IconRightImage = null;
            this.btnPhotos.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnPhotos.OnIdleState.BorderRadius = 1;
            this.btnPhotos.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPhotos.OnIdleState.BorderThickness = 1;
            this.btnPhotos.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnPhotos.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnPhotos.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton8.OnIdleState.IconLeftImage")));
            this.btnPhotos.OnIdleState.IconRightImage = null;
            this.btnPhotos.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPhotos.OnPressedState.BorderRadius = 1;
            this.btnPhotos.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPhotos.OnPressedState.BorderThickness = 1;
            this.btnPhotos.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnPhotos.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPhotos.OnPressedState.IconLeftImage = null;
            this.btnPhotos.OnPressedState.IconRightImage = null;
            this.btnPhotos.Size = new System.Drawing.Size(162, 41);
            this.btnPhotos.TabIndex = 11;
            this.btnPhotos.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPhotos.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPhotos.TextMarginLeft = 0;
            this.btnPhotos.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnPhotos.UseDefaultRadiusAndThickness = true;
            this.btnPhotos.Click += new System.EventHandler(this.btnPhotos_Click);
            // 
            // btnVIP
            // 
            this.btnVIP.AllowAnimations = true;
            this.btnVIP.AllowMouseEffects = true;
            this.btnVIP.AllowToggling = false;
            this.btnVIP.AnimationSpeed = 200;
            this.btnVIP.AutoGenerateColors = false;
            this.btnVIP.AutoRoundBorders = false;
            this.btnVIP.AutoSizeLeftIcon = true;
            this.btnVIP.AutoSizeRightIcon = true;
            this.btnVIP.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.btnVIP.BackColor = System.Drawing.Color.Transparent;
            this.btnVIP.BackColor1 = System.Drawing.Color.Transparent;
            this.btnVIP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVIP.BackgroundImage")));
            this.btnVIP.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVIP.ButtonText = "VIP";
            this.btnVIP.ButtonTextMarginLeft = 0;
            this.btnVIP.ColorContrastOnClick = 45;
            this.btnVIP.ColorContrastOnHover = 45;
            this.btnVIP.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnVIP.CustomizableEdges = borderEdges5;
            this.btnVIP.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnVIP.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVIP.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVIP.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVIP.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnVIP.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnVIP.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnVIP.ForeColor = System.Drawing.Color.Black;
            this.btnVIP.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnVIP.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnVIP.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnVIP.IconMarginLeft = 11;
            this.btnVIP.IconPadding = 10;
            this.btnVIP.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnVIP.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnVIP.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnVIP.IconSize = 100;
            this.btnVIP.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnVIP.IdleBorderRadius = 1;
            this.btnVIP.IdleBorderThickness = 1;
            this.btnVIP.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnVIP.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnVIP.IdleIconLeftImage")));
            this.btnVIP.IdleIconRightImage = null;
            this.btnVIP.IndicateFocus = false;
            this.btnVIP.Location = new System.Drawing.Point(0, 276);
            this.btnVIP.Name = "btnVIP";
            this.btnVIP.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVIP.OnDisabledState.BorderRadius = 1;
            this.btnVIP.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVIP.OnDisabledState.BorderThickness = 1;
            this.btnVIP.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVIP.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVIP.OnDisabledState.IconLeftImage = null;
            this.btnVIP.OnDisabledState.IconRightImage = null;
            this.btnVIP.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnVIP.onHoverState.BorderRadius = 1;
            this.btnVIP.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVIP.onHoverState.BorderThickness = 1;
            this.btnVIP.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnVIP.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnVIP.onHoverState.IconLeftImage = null;
            this.btnVIP.onHoverState.IconRightImage = null;
            this.btnVIP.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnVIP.OnIdleState.BorderRadius = 1;
            this.btnVIP.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVIP.OnIdleState.BorderThickness = 1;
            this.btnVIP.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnVIP.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnVIP.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton5.OnIdleState.IconLeftImage")));
            this.btnVIP.OnIdleState.IconRightImage = null;
            this.btnVIP.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnVIP.OnPressedState.BorderRadius = 1;
            this.btnVIP.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVIP.OnPressedState.BorderThickness = 1;
            this.btnVIP.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnVIP.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnVIP.OnPressedState.IconLeftImage = null;
            this.btnVIP.OnPressedState.IconRightImage = null;
            this.btnVIP.Size = new System.Drawing.Size(162, 41);
            this.btnVIP.TabIndex = 16;
            this.btnVIP.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnVIP.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnVIP.TextMarginLeft = 0;
            this.btnVIP.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnVIP.UseDefaultRadiusAndThickness = true;
            this.btnVIP.Click += new System.EventHandler(this.btnVIP_Click);
            // 
            // btnPlaylist
            // 
            this.btnPlaylist.AllowAnimations = true;
            this.btnPlaylist.AllowMouseEffects = true;
            this.btnPlaylist.AllowToggling = false;
            this.btnPlaylist.AnimationSpeed = 200;
            this.btnPlaylist.AutoGenerateColors = false;
            this.btnPlaylist.AutoRoundBorders = false;
            this.btnPlaylist.AutoSizeLeftIcon = true;
            this.btnPlaylist.AutoSizeRightIcon = true;
            this.btnPlaylist.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.btnPlaylist.BackColor = System.Drawing.Color.Transparent;
            this.btnPlaylist.BackColor1 = System.Drawing.Color.Transparent;
            this.btnPlaylist.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPlaylist.BackgroundImage")));
            this.btnPlaylist.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPlaylist.ButtonText = "Playlist";
            this.btnPlaylist.ButtonTextMarginLeft = 0;
            this.btnPlaylist.ColorContrastOnClick = 45;
            this.btnPlaylist.ColorContrastOnHover = 45;
            this.btnPlaylist.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnPlaylist.CustomizableEdges = borderEdges4;
            this.btnPlaylist.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPlaylist.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPlaylist.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPlaylist.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPlaylist.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnPlaylist.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnPlaylist.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnPlaylist.ForeColor = System.Drawing.Color.Black;
            this.btnPlaylist.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPlaylist.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPlaylist.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPlaylist.IconMarginLeft = 11;
            this.btnPlaylist.IconPadding = 10;
            this.btnPlaylist.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPlaylist.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPlaylist.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPlaylist.IconSize = 100;
            this.btnPlaylist.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnPlaylist.IdleBorderRadius = 1;
            this.btnPlaylist.IdleBorderThickness = 1;
            this.btnPlaylist.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnPlaylist.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnPlaylist.IdleIconLeftImage")));
            this.btnPlaylist.IdleIconRightImage = null;
            this.btnPlaylist.IndicateFocus = false;
            this.btnPlaylist.Location = new System.Drawing.Point(0, 317);
            this.btnPlaylist.Name = "btnPlaylist";
            this.btnPlaylist.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPlaylist.OnDisabledState.BorderRadius = 1;
            this.btnPlaylist.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPlaylist.OnDisabledState.BorderThickness = 1;
            this.btnPlaylist.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPlaylist.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPlaylist.OnDisabledState.IconLeftImage = null;
            this.btnPlaylist.OnDisabledState.IconRightImage = null;
            this.btnPlaylist.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnPlaylist.onHoverState.BorderRadius = 1;
            this.btnPlaylist.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPlaylist.onHoverState.BorderThickness = 1;
            this.btnPlaylist.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnPlaylist.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnPlaylist.onHoverState.IconLeftImage = null;
            this.btnPlaylist.onHoverState.IconRightImage = null;
            this.btnPlaylist.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnPlaylist.OnIdleState.BorderRadius = 1;
            this.btnPlaylist.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPlaylist.OnIdleState.BorderThickness = 1;
            this.btnPlaylist.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnPlaylist.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnPlaylist.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton10.OnIdleState.IconLeftImage")));
            this.btnPlaylist.OnIdleState.IconRightImage = null;
            this.btnPlaylist.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPlaylist.OnPressedState.BorderRadius = 1;
            this.btnPlaylist.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPlaylist.OnPressedState.BorderThickness = 1;
            this.btnPlaylist.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnPlaylist.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPlaylist.OnPressedState.IconLeftImage = null;
            this.btnPlaylist.OnPressedState.IconRightImage = null;
            this.btnPlaylist.Size = new System.Drawing.Size(162, 41);
            this.btnPlaylist.TabIndex = 18;
            this.btnPlaylist.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnPlaylist.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPlaylist.TextMarginLeft = 0;
            this.btnPlaylist.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnPlaylist.UseDefaultRadiusAndThickness = true;
            this.btnPlaylist.Click += new System.EventHandler(this.btnPlaylist_Click);
            // 
            // btnRequest
            // 
            this.btnRequest.AllowAnimations = true;
            this.btnRequest.AllowMouseEffects = true;
            this.btnRequest.AllowToggling = false;
            this.btnRequest.AnimationSpeed = 200;
            this.btnRequest.AutoGenerateColors = false;
            this.btnRequest.AutoRoundBorders = false;
            this.btnRequest.AutoSizeLeftIcon = true;
            this.btnRequest.AutoSizeRightIcon = true;
            this.btnRequest.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.btnRequest.BackColor = System.Drawing.Color.Transparent;
            this.btnRequest.BackColor1 = System.Drawing.Color.Transparent;
            this.btnRequest.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRequest.BackgroundImage")));
            this.btnRequest.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRequest.ButtonText = "Request";
            this.btnRequest.ButtonTextMarginLeft = 0;
            this.btnRequest.ColorContrastOnClick = 45;
            this.btnRequest.ColorContrastOnHover = 45;
            this.btnRequest.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnRequest.CustomizableEdges = borderEdges3;
            this.btnRequest.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRequest.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRequest.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRequest.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRequest.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnRequest.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRequest.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnRequest.ForeColor = System.Drawing.Color.Black;
            this.btnRequest.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRequest.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRequest.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRequest.IconMarginLeft = 11;
            this.btnRequest.IconPadding = 10;
            this.btnRequest.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRequest.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRequest.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRequest.IconSize = 100;
            this.btnRequest.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnRequest.IdleBorderRadius = 1;
            this.btnRequest.IdleBorderThickness = 1;
            this.btnRequest.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnRequest.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnRequest.IdleIconLeftImage")));
            this.btnRequest.IdleIconRightImage = null;
            this.btnRequest.IndicateFocus = false;
            this.btnRequest.Location = new System.Drawing.Point(0, 358);
            this.btnRequest.Name = "btnRequest";
            this.btnRequest.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRequest.OnDisabledState.BorderRadius = 1;
            this.btnRequest.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRequest.OnDisabledState.BorderThickness = 1;
            this.btnRequest.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRequest.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRequest.OnDisabledState.IconLeftImage = null;
            this.btnRequest.OnDisabledState.IconRightImage = null;
            this.btnRequest.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRequest.onHoverState.BorderRadius = 1;
            this.btnRequest.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRequest.onHoverState.BorderThickness = 1;
            this.btnRequest.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRequest.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnRequest.onHoverState.IconLeftImage = null;
            this.btnRequest.onHoverState.IconRightImage = null;
            this.btnRequest.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnRequest.OnIdleState.BorderRadius = 1;
            this.btnRequest.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRequest.OnIdleState.BorderThickness = 1;
            this.btnRequest.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnRequest.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnRequest.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton6.OnIdleState.IconLeftImage")));
            this.btnRequest.OnIdleState.IconRightImage = null;
            this.btnRequest.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRequest.OnPressedState.BorderRadius = 1;
            this.btnRequest.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRequest.OnPressedState.BorderThickness = 1;
            this.btnRequest.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnRequest.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRequest.OnPressedState.IconLeftImage = null;
            this.btnRequest.OnPressedState.IconRightImage = null;
            this.btnRequest.Size = new System.Drawing.Size(162, 41);
            this.btnRequest.TabIndex = 19;
            this.btnRequest.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRequest.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRequest.TextMarginLeft = 0;
            this.btnRequest.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRequest.UseDefaultRadiusAndThickness = true;
            this.btnRequest.Click += new System.EventHandler(this.btnRequest_Click);
            // 
            // btnChat
            // 
            this.btnChat.AllowAnimations = true;
            this.btnChat.AllowMouseEffects = true;
            this.btnChat.AllowToggling = false;
            this.btnChat.AnimationSpeed = 200;
            this.btnChat.AutoGenerateColors = false;
            this.btnChat.AutoRoundBorders = false;
            this.btnChat.AutoSizeLeftIcon = true;
            this.btnChat.AutoSizeRightIcon = true;
            this.btnChat.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.btnChat.BackColor = System.Drawing.Color.Transparent;
            this.btnChat.BackColor1 = System.Drawing.Color.Transparent;
            this.btnChat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChat.BackgroundImage")));
            this.btnChat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChat.ButtonText = "Chat";
            this.btnChat.ButtonTextMarginLeft = 0;
            this.btnChat.ColorContrastOnClick = 45;
            this.btnChat.ColorContrastOnHover = 45;
            this.btnChat.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnChat.CustomizableEdges = borderEdges2;
            this.btnChat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChat.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnChat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnChat.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnChat.ForeColor = System.Drawing.Color.Black;
            this.btnChat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnChat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnChat.IconMarginLeft = 11;
            this.btnChat.IconPadding = 10;
            this.btnChat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnChat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnChat.IconSize = 100;
            this.btnChat.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnChat.IdleBorderRadius = 1;
            this.btnChat.IdleBorderThickness = 1;
            this.btnChat.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnChat.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnChat.IdleIconLeftImage")));
            this.btnChat.IdleIconRightImage = null;
            this.btnChat.IndicateFocus = false;
            this.btnChat.Location = new System.Drawing.Point(0, 399);
            this.btnChat.Name = "btnChat";
            this.btnChat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChat.OnDisabledState.BorderRadius = 1;
            this.btnChat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChat.OnDisabledState.BorderThickness = 1;
            this.btnChat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChat.OnDisabledState.IconLeftImage = null;
            this.btnChat.OnDisabledState.IconRightImage = null;
            this.btnChat.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChat.onHoverState.BorderRadius = 1;
            this.btnChat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChat.onHoverState.BorderThickness = 1;
            this.btnChat.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChat.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnChat.onHoverState.IconLeftImage = null;
            this.btnChat.onHoverState.IconRightImage = null;
            this.btnChat.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnChat.OnIdleState.BorderRadius = 1;
            this.btnChat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChat.OnIdleState.BorderThickness = 1;
            this.btnChat.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnChat.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnChat.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton7.OnIdleState.IconLeftImage")));
            this.btnChat.OnIdleState.IconRightImage = null;
            this.btnChat.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChat.OnPressedState.BorderRadius = 1;
            this.btnChat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChat.OnPressedState.BorderThickness = 1;
            this.btnChat.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnChat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnChat.OnPressedState.IconLeftImage = null;
            this.btnChat.OnPressedState.IconRightImage = null;
            this.btnChat.Size = new System.Drawing.Size(162, 41);
            this.btnChat.TabIndex = 20;
            this.btnChat.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnChat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChat.TextMarginLeft = 0;
            this.btnChat.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnChat.UseDefaultRadiusAndThickness = true;
            this.btnChat.Click += new System.EventHandler(this.btnChat_Click);
            // 
            // btnAbout
            // 
            this.btnAbout.AllowAnimations = true;
            this.btnAbout.AllowMouseEffects = true;
            this.btnAbout.AllowToggling = false;
            this.btnAbout.AnimationSpeed = 200;
            this.btnAbout.AutoGenerateColors = false;
            this.btnAbout.AutoRoundBorders = false;
            this.btnAbout.AutoSizeLeftIcon = true;
            this.btnAbout.AutoSizeRightIcon = true;
            this.btnAbout.AutoValidate = System.Windows.Forms.AutoValidate.EnableAllowFocusChange;
            this.btnAbout.BackColor = System.Drawing.Color.Transparent;
            this.btnAbout.BackColor1 = System.Drawing.Color.Transparent;
            this.btnAbout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAbout.BackgroundImage")));
            this.btnAbout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAbout.ButtonText = "About";
            this.btnAbout.ButtonTextMarginLeft = 0;
            this.btnAbout.ColorContrastOnClick = 45;
            this.btnAbout.ColorContrastOnHover = 45;
            this.btnAbout.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnAbout.CustomizableEdges = borderEdges1;
            this.btnAbout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAbout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAbout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAbout.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAbout.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnAbout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAbout.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAbout.ForeColor = System.Drawing.Color.Black;
            this.btnAbout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAbout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAbout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAbout.IconMarginLeft = 11;
            this.btnAbout.IconPadding = 10;
            this.btnAbout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAbout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAbout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAbout.IconSize = 100;
            this.btnAbout.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnAbout.IdleBorderRadius = 1;
            this.btnAbout.IdleBorderThickness = 1;
            this.btnAbout.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnAbout.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnAbout.IdleIconLeftImage")));
            this.btnAbout.IdleIconRightImage = null;
            this.btnAbout.IndicateFocus = false;
            this.btnAbout.Location = new System.Drawing.Point(0, 440);
            this.btnAbout.Name = "btnAbout";
            this.btnAbout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAbout.OnDisabledState.BorderRadius = 1;
            this.btnAbout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAbout.OnDisabledState.BorderThickness = 1;
            this.btnAbout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAbout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAbout.OnDisabledState.IconLeftImage = null;
            this.btnAbout.OnDisabledState.IconRightImage = null;
            this.btnAbout.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAbout.onHoverState.BorderRadius = 1;
            this.btnAbout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAbout.onHoverState.BorderThickness = 1;
            this.btnAbout.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAbout.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAbout.onHoverState.IconLeftImage = null;
            this.btnAbout.onHoverState.IconRightImage = null;
            this.btnAbout.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnAbout.OnIdleState.BorderRadius = 1;
            this.btnAbout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAbout.OnIdleState.BorderThickness = 1;
            this.btnAbout.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnAbout.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.btnAbout.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton9.OnIdleState.IconLeftImage")));
            this.btnAbout.OnIdleState.IconRightImage = null;
            this.btnAbout.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAbout.OnPressedState.BorderRadius = 1;
            this.btnAbout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAbout.OnPressedState.BorderThickness = 1;
            this.btnAbout.OnPressedState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnAbout.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAbout.OnPressedState.IconLeftImage = null;
            this.btnAbout.OnPressedState.IconRightImage = null;
            this.btnAbout.Size = new System.Drawing.Size(162, 41);
            this.btnAbout.TabIndex = 21;
            this.btnAbout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAbout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAbout.TextMarginLeft = 0;
            this.btnAbout.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAbout.UseDefaultRadiusAndThickness = true;
            this.btnAbout.Click += new System.EventHandler(this.btnAbout_Click);
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 10;
            this.bunifuElipse1.TargetControl = this;
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.btnMaximize);
            this.panel2.Controls.Add(this.btnMinimize);
            this.panel2.Controls.Add(this.btnRestoreDown);
            this.panel2.Controls.Add(this.btnClose);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Right;
            this.panel2.Location = new System.Drawing.Point(551, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(198, 43);
            this.panel2.TabIndex = 4;
            // 
            // btnClose
            // 
            this.btnClose.BackColor = System.Drawing.Color.Transparent;
            this.btnClose.Image = ((System.Drawing.Image)(resources.GetObject("btnClose.Image")));
            this.btnClose.Location = new System.Drawing.Point(170, 11);
            this.btnClose.Name = "btnClose";
            this.btnClose.Size = new System.Drawing.Size(17, 17);
            this.btnClose.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.btnClose.TabIndex = 5;
            this.btnClose.TabStop = false;
            this.btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // btnRestoreDown
            // 
            this.btnRestoreDown.BackColor = System.Drawing.Color.Transparent;
            this.btnRestoreDown.Image = ((System.Drawing.Image)(resources.GetObject("btnRestoreDown.Image")));
            this.btnRestoreDown.Location = new System.Drawing.Point(130, 11);
            this.btnRestoreDown.Name = "btnRestoreDown";
            this.btnRestoreDown.Size = new System.Drawing.Size(17, 17);
            this.btnRestoreDown.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.btnRestoreDown.TabIndex = 6;
            this.btnRestoreDown.TabStop = false;
            this.btnRestoreDown.Click += new System.EventHandler(this.btnRestoreDown_Click);
            // 
            // btnMinimize
            // 
            this.btnMinimize.BackColor = System.Drawing.Color.Transparent;
            this.btnMinimize.Image = ((System.Drawing.Image)(resources.GetObject("btnMinimize.Image")));
            this.btnMinimize.Location = new System.Drawing.Point(90, 11);
            this.btnMinimize.Name = "btnMinimize";
            this.btnMinimize.Size = new System.Drawing.Size(17, 17);
            this.btnMinimize.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.btnMinimize.TabIndex = 7;
            this.btnMinimize.TabStop = false;
            this.btnMinimize.Click += new System.EventHandler(this.btnMinimize_Click);
            // 
            // btnMaximize
            // 
            this.btnMaximize.BackColor = System.Drawing.Color.Transparent;
            this.btnMaximize.Image = ((System.Drawing.Image)(resources.GetObject("btnMaximize.Image")));
            this.btnMaximize.Location = new System.Drawing.Point(130, 11);
            this.btnMaximize.Name = "btnMaximize";
            this.btnMaximize.Size = new System.Drawing.Size(17, 17);
            this.btnMaximize.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.btnMaximize.TabIndex = 8;
            this.btnMaximize.TabStop = false;
            this.btnMaximize.Click += new System.EventHandler(this.btnMaximize_Click);
            // 
            // homeController1
            // 
            this.homeController1.Location = new System.Drawing.Point(162, 114);
            this.homeController1.Name = "homeController1";
            this.homeController1.Size = new System.Drawing.Size(587, 507);
            this.homeController1.TabIndex = 2;
            // 
            // collectionController1
            // 
            this.collectionController1.Location = new System.Drawing.Point(162, 43);
            this.collectionController1.Name = "collectionController1";
            this.collectionController1.Size = new System.Drawing.Size(587, 507);
            this.collectionController1.TabIndex = 3;
            // 
            // Home
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Black;
            this.ClientSize = new System.Drawing.Size(749, 550);
            this.ControlBox = false;
            this.Controls.Add(this.homeController1);
            this.Controls.Add(this.sideBar);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.collectionController1);
            this.ForeColor = System.Drawing.Color.White;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "Home";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Load += new System.EventHandler(this.Home_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.btnEpandandClose)).EndInit();
            this.sideBar.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            this.panel3.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox2)).EndInit();
            this.panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.btnClose)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnRestoreDown)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnMinimize)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.btnMaximize)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label lblTop;
        private System.Windows.Forms.PictureBox btnEpandandClose;
        private System.Windows.Forms.Panel sideBar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnHome;
        private System.Windows.Forms.Panel panel3;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCategories;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnModels;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnCollection;
        private System.Windows.Forms.PictureBox pictureBox2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAbout;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnChat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRequest;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPlaylist;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnVIP;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPhotos;
        private homeController homeController1;
        private collectionController collectionController1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.PictureBox btnMaximize;
        private System.Windows.Forms.PictureBox btnMinimize;
        private System.Windows.Forms.PictureBox btnRestoreDown;
        private System.Windows.Forms.PictureBox btnClose;
    }
}